name: Release

on:
  workflow_dispatch: # Only manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Linux x64
        run: make build-linux_x64

      - name: Build macOS ARM64
        run: make build-macos_arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            shell-cross-env-linux_x64
            shell-cross-env-macos_arm64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
